### ISSUE TITLE
[FR] Have no marker when using the callouts.

### ISSUE THREAD

**Issue by ndharari** [mgmeyers/obsidian-list-callouts#21]
I just dont like the bullet beside the callouts. It would be nice if It could be hidden. 
Thats all!

**Comment by Erik-Handeland** [comment]
Should be able to hide it with CSS snippet, This is what I did for mine:

```css
.lc-list-callout .cm-formatting-list-ul{
display: none;
}
```

**Comment by ndharari** [comment]
Oh, Thank you, this is great. I did a little more work and got this snippet (maybe it helps someone else):

```css
/* No Marker in Live Preview*/
.lc-list-callout .cm-formatting-list-ul {
  display: none;
}

/* No Marker in Reading but markers in subitems*/
.lc-list-callout>.list-bullet:first-child:after {
  height: 0px;
  width: 0px;
  border-radius: 0%;
}

/* No Marker in Print but markers in subitems*/
@media print {
li.lc-list-callout:first-child::marker {
    content: none;
  }
}
```
