### ISSUE TITLE
Allow list callouts to cover line breaks in lists

### ISSUE THREAD

**Issue by burninester** [mgmeyers/obsidian-list-callouts#48]
In live preview mode, list callouts don't cover line breaks, but they do in read mode. I'd like to be able to have this in both read mode and live preview mode. 

Screenshots with examples:

The top screenshot is what happens in read mode and is desired, the bottom screenshot is what happens in live preview and is undesired

![read mode list callout line break example](https://github.com/mgmeyers/obsidian-list-callouts/assets/98194027/76cccb11-4c3c-49d2-9d2f-d81dc906442c)
![live preview list callout line break example](https://github.com/mgmeyers/obsidian-list-callouts/assets/98194027/35076ff5-d61d-464b-ab4c-05cd80418030)

**Comment by churnish** [comment]
This is very much needed indeed!

**Comment by kazerniel** [comment]
+1 request :)

**Comment by churnish** [comment]
This was [shared on Discord](https://discord.com/channels/686053708261228577/702656734631821413/1394857322140012665):

<details><summary>CSS snippet</summary>
<p>

```css
/* List Callouts hardcodes inline styling for the colors
* so we can't access the previous element's inline style.
* You will have to manually put them in here */

/* Our color variables */

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout[data-callout="💚"]+div.cm-line.HyperMD-list-line-nobullet {
    --lc-callout-color: 158, 202, 140;
}

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout[data-callout="🤍"]+div.cm-line.HyperMD-list-line-nobullet {
    --lc-callout-color: 158, 158, 158;
}

/* No padding or curved border between the lines to make it look seamless*/
.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout:has(+ div.cm-line.HyperMD-list-line-nobullet>span.cm-list-1) {
    padding-bottom: 0px;
}

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout:has(+ div.cm-line.HyperMD-list-line-nobullet>span.cm-list-1)>span.lc-list-bg:after {
    border-bottom-right-radius: 0px !important;
    border-bottom-left-radius: 0px !important;
}

/* Fixing the weird offset (kind of) */

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout+div.cm-line.HyperMD-list-line-nobullet:has(span.cm-list-1) {
    display: flex;
    padding-inline-start: 0px !important;
    text-indent: 0px !important;
}

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout+div.cm-line.HyperMD-list-line-nobullet>span.cm-hmd-list-indent {
    margin-left: 5px;
    /* You'll probably have to adjust the above. It's set somewhere in app.js
    * and I don't feel like deconstructing where it gets the number from, but it
    * has something to do with character width.*/

    background-color: rgba(var(--lc-callout-color), var(--lc-bg-opacity-light));
}

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout+div.cm-line.HyperMD-list-line-nobullet>span.cm-list-1 {
    background-color: rgba(var(--lc-callout-color), var(--lc-bg-opacity-light));
    flex-grow: 2;
}
```

</p>
</details> 

You'd need to replace `💚` and `🤍` here with what the triggers than you have set up.

**Comment by kazerniel** [comment]
@greetclammy Sorry for the delayed response, and thank you, this is really helpful!

**Comment by kazerniel** [comment]
I just realised that unfortunately this snippet doesn't work if the list callout is not a top level list item, but indented.

**Comment by churnish** [comment]
@kazerniel  Could probably be rectified. I would ask Claude for help.

**Comment by kazerniel** [comment]
Sorry, I'd rather not touch genAI. I tried to poke around the code and gave it some indentation support, but there are some odd gaps left that I don't have the time to try to fix right now.

<img width="156" height="109" alt="Image" src="https://github.com/user-attachments/assets/2458094a-b400-4f9a-8ab7-2f56189e15a6" />

<details>
<summary>the modified code snippet</summary>

```css
/* List Callouts hardcodes inline styling for the colors
* so we can't access the previous element's inline style.
* You will have to manually put them in here */

/* Our color variables */

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout[data-callout="💚"]+div.cm-line.HyperMD-list-line-nobullet {
    --lc-callout-color: 158, 202, 140;
}

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout[data-callout="🤍"]+div.cm-line.HyperMD-list-line-nobullet {
    --lc-callout-color: 158, 158, 158;
}

/* No padding or curved border between the lines to make it look seamless*/

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout:has(+ div.cm-line.HyperMD-list-line-nobullet > :is(
	span.cm-list-1,
	span.cm-list-2,
	span.cm-list-3,
	span.cm-list-4,
	span.cm-list-5,
	span.cm-list-6,
	span.cm-list-7,
	span.cm-list-8,
	span.cm-list-9
	))
{
	padding-bottom: 0px;
}

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout + div.cm-line.HyperMD-list-line-nobullet
{
	padding-top: 0;
}

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout:has(+ div.cm-line.HyperMD-list-line-nobullet > span.cm-list-1) > span.lc-list-bg:after
{
	border-bottom-right-radius: 0px !important;
	border-bottom-left-radius: 0px !important;
}

/* Fixing the weird offset (kind of) */

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout + div.cm-line.HyperMD-list-line-nobullet:has(:is(
	span.cm-list-1,
	span.cm-list-2,
	span.cm-list-3,
	span.cm-list-4,
	span.cm-list-5,
	span.cm-list-6,
	span.cm-list-7,
	span.cm-list-8,
	span.cm-list-9
	))
{
	display: flex;
	padding-inline-start: 0px !important;
	text-indent: 0px !important;
}

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout + div.cm-line.HyperMD-list-line-nobullet > span.cm-hmd-list-indent,
.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout:has( + div.cm-line.HyperMD-list-line-nobullet) > span.cm-hmd-list-indent
{
	margin-left: 5px;
	/* You'll probably have to adjust the above. It's set somewhere in app.js
    * and I don't feel like deconstructing where it gets the number from, but it
    * has something to do with character width.*/

	background-color: rgba(var(--lc-callout-color), var(--lc-bg-opacity-light));
}

.markdown-source-view.is-live-preview.mod-cm6 .lc-list-callout + div.cm-line.HyperMD-list-line-nobullet > :is(
	span.cm-list-1,
	span.cm-list-2,
	span.cm-list-3,
	span.cm-list-4,
	span.cm-list-5,
	span.cm-list-6,
	span.cm-list-7,
	span.cm-list-8,
	span.cm-list-9
)
{
	background-color: rgba(var(--lc-callout-color), var(--lc-bg-opacity-light));
	flex-grow: 2;
}
```

</details>
